### ISSUE TITLE
static vs. shared lib

### ISSUE THREAD

**Issue by loriab** [conda-forge/libecpint-feedstock#4]
### Comment:

Hi, I noticed that the recipe builds the static library, rather than the shared as is common for conda: https://github.com/conda-forge/libecpint-feedstock/blob/main/recipe/meta.yaml#L31-L32 . Was there a technical reason for this, or would you be open to a switch to shared?

For reference, I've got an outline for a shared lib recipe https://github.com/psi4/psi4meta/blob/master/conda-recipes/libecpint/build.sh#L34-L50 

A few other unimplemented plans I've had for ecpint:
* turn off xml by default
* use cerf instead of vendoring Faddeeva https://github.com/robashaw/libecpint/blob/master/src/CMakeLists.txt#L56-L78
* spliting c and py packages
* (as mentioned) use shared instead of static libs

I haven't looked at libecpint recently, but I thought I'd inquire, and see what you think and need. Thanks!

**Comment by jan-janssen** [comment]
@loriab I am fine with switching to a shared library, I primarily use `libecpint` for https://github.com/conda-forge/votca-feedstock so as long as that works with the shared library we should be fine. @junghans Is there any reason why `votca` should not work with `libecpint` compiled as shared library?

**Comment by junghans** [comment]
Nope, we use shared everywhere else!

**Comment by loriab** [comment]
Great, thanks! I don't know when I'll get to it (I prepped `cerf` CMake in Dec 2021), but I'll make some PRs, starting with shared.
